apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: ">=1.16.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  interval: 24h
  install:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: "true"
    k8sServiceHost: "kube.local.arsolitt.tech"
    k8sServicePort: "6443"
    operator:
      replicas: 1
