apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: default
spec:
  releaseName: contour
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: contour
        namespace: default
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values:
