apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
spec:
  releaseName: dragonfly
  chart:
    spec:
      chart: dragonfly
      sourceRef:
        kind: HelmRepository
        name: dragonfly
  interval: 24h
  install:
    remediation:
      retries: 3
  values:
