apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager
patches:
  - target:
      kind: HelmRelease
      name: cert-manager
    patch: |
      - op: replace
        path: /spec/values
        value:
          crds:
            enabled: true
            keep: false
          resources:
          requests:
            cpu: 10m
            memory: 32Mi
          prometheus:
            enabled: false
