apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical-store-dev
  namespace: external-secrets
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: default
            name: infisical-auth
          clientSecret:
            key: clientSecret
            namespace: default
            name: infisical-auth
      secretsScope:
        projectSlug: tech-e-zvh
        environmentSlug: dev
        secretsPath: /
      hostAPI: https://app.infisical.com
