apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-delete
  labels:
    app: local-path-storage-class
    policy: delete
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
