apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  releaseName: node-exporter
  chart:
    spec:
      chart: node-exporter
      sourceRef:
        kind: HelmRepository
        name: node-exporter
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values:
