apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fast
patches:
  - target:
      kind: ConfigMap
      name: local-path-config
    patch: |
      - op: replace
        path: /data/config.json
        value: |-
          {
            "nodePathMap":[
              {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/storage/fast", "/storage/universal", "/storage/basic"]
              }
            ]
          }
