apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: tools
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: tools
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values:
    reloader:
      autoReloadAll: false
      readOnlyRootFileSystem: true
      deployment:
        livenessProbe:
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          timeoutSeconds: 15
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "10m"
            memory: "64Mi"
