apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values:
    controller:
      nodeSelector:
        ingress: "true"
      tolerations:
        - key: "metallb"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
    speaker:
      nodeSelector:
        ingress: "true"
      tolerations:
        - key: "metallb"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
