apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: tech
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  selectAllByDefault: true
  vmAgentExternalLabelName: agent
  remoteWrite:
    - url: "http://vminsert-tech.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
  remoteWriteSettings:
    label:
      cluster: tech
