apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: tech
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector:
    matchNames:
      - monitoring
  podScrapeNamespaceSelector:
    matchNames:
      - monitoring
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector:
    matchNames:
      - monitoring
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector:
    matchNames:
      - monitoring
  replicaCount: 1
  remoteWrite:
    - url: "http://vminsert-tech.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
