apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: tech
  namespace: monitoring
spec:
  selectAllByDefault: true
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector:
    {}
    # matchLabels:
    #   team: kubernetes
    #   app.kubernetes.io/component: monitoring
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  remoteWrite:
    - url: "http://vminsert-tech.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
