apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/contour-ingress
  - namespace.yaml
patches:
  - target:
      kind: HelmRelease
      name: contour
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: contour
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: ingress
  - target:
      kind: HelmRepository
      name: contour
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: contour
    patch: |
      - op: replace
        path: /spec/values
        value:
          contour:
            nodeSelector:
              ingress: "true"
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2
                memory: 2048Mi

          envoy:
            nodeSelector:
              ingress: "true"
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2
                memory: 2048Mi

          defaultBackend:
            nodeSelector:
              ingress: "true"
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2
                memory: 2048Mi
