apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zalando-operator
spec:
  releaseName: zalando-operator
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-pg
  interval: 24h
  install:
    remediation:
      retries: 3
  values:
