apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zalando-pg
  namespace: default
spec:
  interval: 24h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
