apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cilium
patches:
  - target:
      kind: HelmRelease
      name: cilium
    patch: |
      - op: replace
        path: /spec/values
        value:
          kubeProxyReplacement: "true"
          k8sServiceHost: "kube.local.arsolitt.tech"
          k8sServicePort: "6443"
          operator:
            replicas: 1
