apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/nginx-ingress
patches:
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: ingress
  - target:
      kind: HelmRepository
      name: nginx
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /spec/values
        value:
          controller:
            kind: DaemonSet
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: ingress
                          operator: In
                          values:
                            - "true"
            tolerations:
              - key: "ingress"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
            resources:
              limits:
                cpu: 1
                memory: 1024Mi
              requests:
                cpu: 10m
                memory: 50Mi
            service:
              enabled: true
              external:
                enabled: true
              annotations:
                metallb.universe.tf/loadBalancerIPs: "192.168.1.8"
            config:
              use-forwarded-headers: "true"
              use-http2: "true"
            allowSnippetAnnotations: true
            extraArgs:
              sort-backends: "true"
            metrics:
              port: 10254
              portName: metrics
              enabled: true
              service:
                annotations: {}
                # prometheus.io/scrape: "true"
                # prometheus.io/port: "10254"
              serviceMonitor:
                enabled: false
                additionalLabels: {}
                annotations: {}
                ## The label to use to retrieve the job name from.
                ## jobLabel: "app.kubernetes.io/name"
                jobLabel: "app.kubernetes.io/name"
                namespace: ""
                namespaceSelector: {}
                ## Default: scrape .Release.Namespace or namespaceOverride only
                ## To scrape all, use the following:
                ## namespaceSelector:
                ##   any: true
                scrapeInterval: 30s
                # honorLabels: true
                targetLabels: []
                relabelings: []
                metricRelabelings: []
          revisionHistoryLimit: 2
          tcp: {}
          #  "8080": "default/example-tcp-svc:9000"

          # -- UDP service key-value pairs
          ## Ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/exposing-tcp-udp-services.md
          ##
          udp: {}
          #  "53": "kube-system/kube-dns:53"
