apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/nginx-ingress
patches:
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: ingress
  - target:
      kind: HelmRepository
      name: nginx
    patch: |
      - op: replace
        path: /metadata/namespace
        value: ingress
  - target:
      kind: HelmRelease
      name: nginx
    patch: |
      - op: replace
        path: /spec/values
        value:
          controller:
            kind: DaemonSet
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: ingress
                          operator: In
                          values:
                            - "true"
            tolerations:
              - key: "ingress"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
            resources:
              limits:
                cpu: 2
                memory: 2048Mi
              requests:
                cpu: 100m
                memory: 128Mi
            service:
              enabled: true
              external:
                enabled: true
              annotations:
                metallb.universe.tf/loadBalancerIPs: "192.168.1.8"
            config:
              use-forwarded-headers: "true"
              use-http2: "true"
              worker-processes: "4"
              plugins: "crowdsec"
              lua-shared-dicts: "crowdsec_cache: 50m"
            allowSnippetAnnotations: true
            extraVolumes:
              - name: crowdsec-bouncer-plugin
                emptyDir: {}
            extraInitContainers:
              - name: init-clone-crowdsec-bouncer
                image: crowdsecurity/lua-bouncer-plugin
                imagePullPolicy: IfNotPresent
                envFrom:
                  - secretRef:
                      name: nginx-env
                  # env:
                  #   - name: API_URL
                  #     valueFrom:
                  #       secretKeyRef:
                  #         name: nginx-env
                  #         key: API_URL
                  #   - name: API_KEY
                  #     valueFrom:
                  #       secretKeyRef:
                  #         name: nginx-env
                  #         key: API_KEY
                  - name: BOUNCER_CONFIG
                    value: "/crowdsec/crowdsec-bouncer.conf"
                command:
                  [
                    "sh",
                    "-c",
                    "sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp -R /crowdsec/* /lua_plugins/crowdsec/",
                  ]
                volumeMounts:
                  - name: crowdsec-bouncer-plugin
                    mountPath: /lua_plugins
            extraVolumeMounts:
              - name: crowdsec-bouncer-plugin
                mountPath: /etc/nginx/lua/plugins/crowdsec
                subPath: crowdsec
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                jobLabel: "app.kubernetes.io/name"
          revisionHistoryLimit: 2
          tcp: {}
          #  "8080": "default/example-tcp-svc:9000"
          udp: {}
          #  "53": "kube-system/kube-dns:53"
