apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/external-secrets
patches:
  - target:
      kind: HelmRelease
      name: external-secrets
    patch: |
      - op: replace
        path: /metadata/namespace
        value: external-secrets
  - target:
      kind: HelmRelease
      name: external-secrets
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: external-secrets
  - target:
      kind: HelmRepository
      name: external-secrets
    patch: |
      - op: replace
        path: /metadata/namespace
        value: external-secrets
  - target:
      kind: HelmRelease
      name: external-secrets
    patch: |
      - op: replace
        path: /spec/values
        value:
          replicaCount: 1
          leaderElect: false
          revisionHistoryLimit: 2
          extendedMetricLabels: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 256Mi

          webhook:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 256Mi
          certController:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 256Mi
