apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dragonfly
  - namespace.yaml
patches:
  - target:
      kind: HelmRelease
      name: dragonfly
    patch: |
      - op: replace
        path: /metadata/namespace
        value: data
  - target:
      kind: HelmRelease
      name: dragonfly
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: data
  - target:
      kind: HelmRepository
      name: dragonfly
    patch: |
      - op: replace
        path: /metadata/namespace
        value: data
  - target:
      kind: HelmRelease
      name: dragonfly
    patch: |
      - op: replace
        path: /spec/values
        value:
