apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/node-exporter
patches:
  - target:
      kind: HelmRelease
      name: node-exporter
    patch: |
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: HelmRelease
      name: node-exporter
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: monitoring
  - target:
      kind: HelmRepository
      name: node-exporter
    patch: |
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: HelmRelease
      name: node-exporter
    patch: |
      - op: replace
        path: /spec/values
        value:
          revisionHistoryLimit: 2
          fullnameOverride: "node-exporter"

          prometheus:
            monitor:
              enabled: true

          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 32Mi
