apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: data
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: data
  interval: 24h
  install:
    remediation:
      retries: 3

  values:
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly no
      # Disable RDB persistence, AOF persistence already enabled.
      save ""
      databases 32
    master:
      count: 1
      revisionHistoryLimit: 3
      extraFlags:
        - "--databases 32"
      startupProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 15
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1024Mi
      tolerations:
        - key: stateful
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: redis
                    operator: In
                    values:
                      - "true"
      persistence:
        enabled: false
    replica:
      replicaCount: 3
      revisionHistoryLimit: 3
      extraFlags:
        - "--databases 32"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1024Mi
      tolerations:
        - key: stateful
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: redis
                    operator: In
                    values:
                      - "true"
      persistence:
        enabled: false

    sentinel:
      extraFlags:
        - "--databases 32"
      enabled: true
      masterSet: dev
      quorum: 2
      automateClusterRecovery: true
      redisShutdownWaitFailover: true
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1024Mi
