apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/metallb
patches:
  - target:
      kind: HelmRelease
      name: metallb
    patch: |
      - op: replace
        path: /spec/values
        value: |
          controller:
            nodeSelector:
              metallb: "true"
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 128Mi
          speaker:
            nodeSelector:
              metallb: "true"
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 128Mi
