apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zalando-operator
  namespace: default
spec:
  releaseName: zalando-operator
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-pg
        namespace: default
  interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
