apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
  namespace: default
spec:
  releaseName: vm-operator
  chart:
    spec:
      chart: vm-operator
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: default
  interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
