apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "authentik-env"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "authentik-env"

  # This is a list of basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  # The list is OR'd together, so if any of the namespaceSelectors match the namespace,
  # the ExternalSecret will be deployed to that namespace.
  namespaceSelectors:
    - matchLabels:
        authentik: "true"

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: infisical-store-prod

    refreshInterval: "1h"
    target:
      name: authentik-env
      deletionPolicy: Delete
    dataFrom:
      - find:
          path: authentik/*
