apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pg-tech
  namespace: data
spec:
  teamId: "tech"
  volume:
    size: 1Gi
    storageClass: local-fast-retain
  numberOfInstances: 3
  enableMasterLoadBalancer: false
  enableMasterPoolerLoadBalancer: false
  enableConnectionPooler: true
  enableLogicalBackup: false
  users:
    postgres: # database owner
      - superuser
      - createdb
    # harbor: []
    grafana: []
    authentik: []
  databases:
    postgres: postgres # dbname: owner
    # harbor: harbor
    grafana: grafana
    authentik: authentik
  preparedDatabases:
    postgres: {}
  postgresql:
    version: "16"
    parameters:
      max_connections: "100"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: postgres
              operator: In
              values:
                - "true"
  connectionPooler:
    numberOfInstances: 1
