apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-tech
  namespace: data
spec:
  dependsOn:
    - name: zalando-operator
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: apps/tech/zalando-postgres/pg-tech
  prune: true
  # wait: true
