apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ces-grafana-env.yaml
  - css-grafana-prod.yaml
  - ../../base/grafana
patches:
  - target:
      kind: HelmRelease
      name: grafana
    patch: |
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: HelmRelease
      name: grafana
    patch: |
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: monitoring
  - target:
      kind: HelmRepository
      name: grafana
    patch: |
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: HelmRelease
      name: grafana
    patch: |
      - op: replace
        path: /spec/values
        value:
          testFramework:
            enabled: false
            # resources:
            #   limits:
            #     cpu: 50m
            #     memory: 64Mi
            #   requests:
            #     cpu: 1m
            #     memory: 16Mi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              # projectcontour.io/websocket-routes: /api/live/ws
            hosts:
              - grafana.arsolitt.tech
            extraPaths:
              - path: /api/live/ws
                pathType: Prefix
                backend:
                  service:
                    name: grafana
                    port:
                      number: 80
            tls:
              - secretName: grafana-arsolitt-tech-tls
                hosts:
                  - grafana.arsolitt.tech
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          persistence:
            enabled: false
            storageClassName: "local-path"
          initChownData:
            enabled: true
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
              requests:
                cpu: 10m
                memory: 5Mi
          adminPassword: ""
          grafana.ini:
            auth:
              signout_redirect_url: "https://authentik.arsolitt.tech/application/o/grafana/end-session/"
              auto_login: true
            auth.generic_oauth:
              name: authentik
              enabled: true
              client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
              client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
              scopes: "openid profile email"
              auth_url: "https://authentik.arsolitt.tech/application/o/authorize/"
              token_url: "https://authentik.arsolitt.tech/application/o/token/"
              api_url: "https://authentik.arsolitt.tech/application/o/userinfo/"
              role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
            smtp:
              enabled: false
            server:
              root_url: https://grafana.arsolitt.tech
            database:
              type: postgres
              url: $__file{/etc/secrets/pg_config/pg_conn_string}
          extraSecretMounts:
            - name: auth-generic-oauth-secret-mount
              secretName: grafana-env
              defaultMode: 0440
              mountPath: /etc/secrets/auth_generic_oauth
              readOnly: true
            - name: pg-config
              secretName: grafana-env
              defaultMode: 0440
              mountPath: /etc/secrets/pg_config
              readOnly: true
          sidecar:
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 16Mi
          revisionHistoryLimit: 1
          imageRenderer:
            enabled: true
            revisionHistoryLimit: 1
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 64Mi
          useStatefulSet: false
