apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  releaseName: dragonfly
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: dragonfly-operator-system
  interval: 24h
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
